//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Mastermind {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
//    [global::System.Serializable()]
//    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
//    [global::System.ComponentModel.ToolboxItem(true)]
//    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
//    [global::System.Xml.Serialization.XmlRootAttribute("mastermindHighscoreDataSet")]
//    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
//    public partial class mastermindHighscoreDataSet : global::System.Data.DataSet {
        
//        private highscoreDataTable tablehighscore;
        
//        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        public mastermindHighscoreDataSet() {
//            this.BeginInit();
//            this.InitClass();
//            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
//            base.Tables.CollectionChanged += schemaChangedHandler;
//            base.Relations.CollectionChanged += schemaChangedHandler;
//            this.EndInit();
//        }
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        protected mastermindHighscoreDataSet(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
//                base(info, context, false) {
//            if ((this.IsBinarySerialized(info, context) == true)) {
//                this.InitVars(false);
//                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
//                this.Tables.CollectionChanged += schemaChangedHandler1;
//                this.Relations.CollectionChanged += schemaChangedHandler1;
//                return;
//            }
//            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
//            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
//                global::System.Data.DataSet ds = new global::System.Data.DataSet();
//                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
//                if ((ds.Tables["highscore"] != null)) {
//                    base.Tables.Add(new highscoreDataTable(ds.Tables["highscore"]));
//                }
//                this.DataSetName = ds.DataSetName;
//                this.Prefix = ds.Prefix;
//                this.Namespace = ds.Namespace;
//                this.Locale = ds.Locale;
//                this.CaseSensitive = ds.CaseSensitive;
//                this.EnforceConstraints = ds.EnforceConstraints;
//                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
//                this.InitVars();
//            }
//            else {
//                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
//            }
//            this.GetSerializationData(info, context);
//            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
//            base.Tables.CollectionChanged += schemaChangedHandler;
//            this.Relations.CollectionChanged += schemaChangedHandler;
//        }
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        [global::System.ComponentModel.Browsable(false)]
//        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
//        public highscoreDataTable highscore {
//            get {
//                return this.tablehighscore;
//            }
//        }
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        [global::System.ComponentModel.BrowsableAttribute(true)]
//        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
//        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
//            get {
//                return this._schemaSerializationMode;
//            }
//            set {
//                this._schemaSerializationMode = value;
//            }
//        }
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
//        public new global::System.Data.DataTableCollection Tables {
//            get {
//                return base.Tables;
//            }
//        }
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
//        public new global::System.Data.DataRelationCollection Relations {
//            get {
//                return base.Relations;
//            }
//        }
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        protected override void InitializeDerivedDataSet() {
//            this.BeginInit();
//            this.InitClass();
//            this.EndInit();
//        }
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        public override global::System.Data.DataSet Clone() {
//            mastermindHighscoreDataSet cln = ((mastermindHighscoreDataSet)(base.Clone()));
//            cln.InitVars();
//            cln.SchemaSerializationMode = this.SchemaSerializationMode;
//            return cln;
//        }
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        protected override bool ShouldSerializeTables() {
//            return false;
//        }
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        protected override bool ShouldSerializeRelations() {
//            return false;
//        }
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
//            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
//                this.Reset();
//                global::System.Data.DataSet ds = new global::System.Data.DataSet();
//                ds.ReadXml(reader);
//                if ((ds.Tables["highscore"] != null)) {
//                    base.Tables.Add(new highscoreDataTable(ds.Tables["highscore"]));
//                }
//                this.DataSetName = ds.DataSetName;
//                this.Prefix = ds.Prefix;
//                this.Namespace = ds.Namespace;
//                this.Locale = ds.Locale;
//                this.CaseSensitive = ds.CaseSensitive;
//                this.EnforceConstraints = ds.EnforceConstraints;
//                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
//                this.InitVars();
//            }
//            else {
//                this.ReadXml(reader);
//                this.InitVars();
//            }
//        }
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
//            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
//            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
//            stream.Position = 0;
//            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
//        }
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        internal void InitVars() {
//            this.InitVars(true);
//        }
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        internal void InitVars(bool initTable) {
//            this.tablehighscore = ((highscoreDataTable)(base.Tables["highscore"]));
//            if ((initTable == true)) {
//                if ((this.tablehighscore != null)) {
//                    this.tablehighscore.InitVars();
//                }
//            }
//        }
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        private void InitClass() {
//            this.DataSetName = "mastermindHighscoreDataSet";
//            this.Prefix = "";
//            this.Namespace = "http://tempuri.org/mastermindHighscoreDataSet.xsd";
//            this.EnforceConstraints = true;
//            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
//            this.tablehighscore = new highscoreDataTable();
//            base.Tables.Add(this.tablehighscore);
//        }
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        private bool ShouldSerializehighscore() {
//            return false;
//        }
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
//            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
//                this.InitVars();
//            }
//        }
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
//            mastermindHighscoreDataSet ds = new mastermindHighscoreDataSet();
//            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
//            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
//            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
//            any.Namespace = ds.Namespace;
//            sequence.Items.Add(any);
//            type.Particle = sequence;
//            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
//            if (xs.Contains(dsSchema.TargetNamespace)) {
//                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
//                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
//                try {
//                    global::System.Xml.Schema.XmlSchema schema = null;
//                    dsSchema.Write(s1);
//                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
//                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
//                        s2.SetLength(0);
//                        schema.Write(s2);
//                        if ((s1.Length == s2.Length)) {
//                            s1.Position = 0;
//                            s2.Position = 0;
//                            for (; ((s1.Position != s1.Length) 
//                                        && (s1.ReadByte() == s2.ReadByte())); ) {
//                                ;
//                            }
//                            if ((s1.Position == s1.Length)) {
//                                return type;
//                            }
//                        }
//                    }
//                }
//                finally {
//                    if ((s1 != null)) {
//                        s1.Close();
//                    }
//                    if ((s2 != null)) {
//                        s2.Close();
//                    }
//                }
//            }
//            xs.Add(dsSchema);
//            return type;
//        }
        
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        public delegate void highscoreRowChangeEventHandler(object sender, highscoreRowChangeEvent e);
        
//        /// <summary>
//        ///Represents the strongly named DataTable class.
//        ///</summary>
//        [global::System.Serializable()]
//        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
//        public partial class highscoreDataTable : global::System.Data.TypedTableBase<highscoreRow> {
            
//            private global::System.Data.DataColumn columnnaam;
            
//            private global::System.Data.DataColumn columnscore;
            
//            private global::System.Data.DataColumn columntijd;
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            public highscoreDataTable() {
//                this.TableName = "highscore";
//                this.BeginInit();
//                this.InitClass();
//                this.EndInit();
//            }
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            internal highscoreDataTable(global::System.Data.DataTable table) {
//                this.TableName = table.TableName;
//                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
//                    this.CaseSensitive = table.CaseSensitive;
//                }
//                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
//                    this.Locale = table.Locale;
//                }
//                if ((table.Namespace != table.DataSet.Namespace)) {
//                    this.Namespace = table.Namespace;
//                }
//                this.Prefix = table.Prefix;
//                this.MinimumCapacity = table.MinimumCapacity;
//            }
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            protected highscoreDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
//                    base(info, context) {
//                this.InitVars();
//            }
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            public global::System.Data.DataColumn naamColumn {
//                get {
//                    return this.columnnaam;
//                }
//            }
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            public global::System.Data.DataColumn scoreColumn {
//                get {
//                    return this.columnscore;
//                }
//            }
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            public global::System.Data.DataColumn tijdColumn {
//                get {
//                    return this.columntijd;
//                }
//            }
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            [global::System.ComponentModel.Browsable(false)]
//            public int Count {
//                get {
//                    return this.Rows.Count;
//                }
//            }
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            public highscoreRow this[int index] {
//                get {
//                    return ((highscoreRow)(this.Rows[index]));
//                }
//            }
            
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            public event highscoreRowChangeEventHandler highscoreRowChanging;
            
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            public event highscoreRowChangeEventHandler highscoreRowChanged;
            
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            public event highscoreRowChangeEventHandler highscoreRowDeleting;
            
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            public event highscoreRowChangeEventHandler highscoreRowDeleted;
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            public void AddhighscoreRow(highscoreRow row) {
//                this.Rows.Add(row);
//            }
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            public highscoreRow AddhighscoreRow(string naam, int score, System.DateTime tijd) {
//                highscoreRow rowhighscoreRow = ((highscoreRow)(this.NewRow()));
//                object[] columnValuesArray = new object[] {
//                        naam,
//                        score,
//                        tijd};
//                rowhighscoreRow.ItemArray = columnValuesArray;
//                this.Rows.Add(rowhighscoreRow);
//                return rowhighscoreRow;
//            }
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            public override global::System.Data.DataTable Clone() {
//                highscoreDataTable cln = ((highscoreDataTable)(base.Clone()));
//                cln.InitVars();
//                return cln;
//            }
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            protected override global::System.Data.DataTable CreateInstance() {
//                return new highscoreDataTable();
//            }
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            internal void InitVars() {
//                this.columnnaam = base.Columns["naam"];
//                this.columnscore = base.Columns["score"];
//                this.columntijd = base.Columns["tijd"];
//            }
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            private void InitClass() {
//                this.columnnaam = new global::System.Data.DataColumn("naam", typeof(string), null, global::System.Data.MappingType.Element);
//                base.Columns.Add(this.columnnaam);
//                this.columnscore = new global::System.Data.DataColumn("score", typeof(int), null, global::System.Data.MappingType.Element);
//                base.Columns.Add(this.columnscore);
//                this.columntijd = new global::System.Data.DataColumn("tijd", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
//                base.Columns.Add(this.columntijd);
//                this.columnnaam.MaxLength = 255;
//                this.columntijd.AllowDBNull = false;
//            }
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            public highscoreRow NewhighscoreRow() {
//                return ((highscoreRow)(this.NewRow()));
//            }
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
//                return new highscoreRow(builder);
//            }
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            protected override global::System.Type GetRowType() {
//                return typeof(highscoreRow);
//            }
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
//                base.OnRowChanged(e);
//                if ((this.highscoreRowChanged != null)) {
//                    this.highscoreRowChanged(this, new highscoreRowChangeEvent(((highscoreRow)(e.Row)), e.Action));
//                }
//            }
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
//                base.OnRowChanging(e);
//                if ((this.highscoreRowChanging != null)) {
//                    this.highscoreRowChanging(this, new highscoreRowChangeEvent(((highscoreRow)(e.Row)), e.Action));
//                }
//            }
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
//                base.OnRowDeleted(e);
//                if ((this.highscoreRowDeleted != null)) {
//                    this.highscoreRowDeleted(this, new highscoreRowChangeEvent(((highscoreRow)(e.Row)), e.Action));
//                }
//            }
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
//                base.OnRowDeleting(e);
//                if ((this.highscoreRowDeleting != null)) {
//                    this.highscoreRowDeleting(this, new highscoreRowChangeEvent(((highscoreRow)(e.Row)), e.Action));
//                }
//            }
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            public void RemovehighscoreRow(highscoreRow row) {
//                this.Rows.Remove(row);
//            }
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
//                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
//                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
//                mastermindHighscoreDataSet ds = new mastermindHighscoreDataSet();
//                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
//                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
//                any1.MinOccurs = new decimal(0);
//                any1.MaxOccurs = decimal.MaxValue;
//                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
//                sequence.Items.Add(any1);
//                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
//                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
//                any2.MinOccurs = new decimal(1);
//                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
//                sequence.Items.Add(any2);
//                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
//                attribute1.Name = "namespace";
//                attribute1.FixedValue = ds.Namespace;
//                type.Attributes.Add(attribute1);
//                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
//                attribute2.Name = "tableTypeName";
//                attribute2.FixedValue = "highscoreDataTable";
//                type.Attributes.Add(attribute2);
//                type.Particle = sequence;
//                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
//                if (xs.Contains(dsSchema.TargetNamespace)) {
//                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
//                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
//                    try {
//                        global::System.Xml.Schema.XmlSchema schema = null;
//                        dsSchema.Write(s1);
//                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
//                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
//                            s2.SetLength(0);
//                            schema.Write(s2);
//                            if ((s1.Length == s2.Length)) {
//                                s1.Position = 0;
//                                s2.Position = 0;
//                                for (; ((s1.Position != s1.Length) 
//                                            && (s1.ReadByte() == s2.ReadByte())); ) {
//                                    ;
//                                }
//                                if ((s1.Position == s1.Length)) {
//                                    return type;
//                                }
//                            }
//                        }
//                    }
//                    finally {
//                        if ((s1 != null)) {
//                            s1.Close();
//                        }
//                        if ((s2 != null)) {
//                            s2.Close();
//                        }
//                    }
//                }
//                xs.Add(dsSchema);
//                return type;
//            }
//        }
        
//        /// <summary>
//        ///Represents strongly named DataRow class.
//        ///</summary>
//        public partial class highscoreRow : global::System.Data.DataRow {
            
//            private highscoreDataTable tablehighscore;
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            internal highscoreRow(global::System.Data.DataRowBuilder rb) : 
//                    base(rb) {
//                this.tablehighscore = ((highscoreDataTable)(this.Table));
//            }
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            public string naam {
//                get {
//                    try {
//                        return ((string)(this[this.tablehighscore.naamColumn]));
//                    }
//                    catch (global::System.InvalidCastException e) {
//                        throw new global::System.Data.StrongTypingException("The value for column \'naam\' in table \'highscore\' is DBNull.", e);
//                    }
//                }
//                set {
//                    this[this.tablehighscore.naamColumn] = value;
//                }
//            }
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            public int score {
//                get {
//                    try {
//                        return ((int)(this[this.tablehighscore.scoreColumn]));
//                    }
//                    catch (global::System.InvalidCastException e) {
//                        throw new global::System.Data.StrongTypingException("The value for column \'score\' in table \'highscore\' is DBNull.", e);
//                    }
//                }
//                set {
//                    this[this.tablehighscore.scoreColumn] = value;
//                }
//            }
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            public System.DateTime tijd {
//                get {
//                    return ((global::System.DateTime)(this[this.tablehighscore.tijdColumn]));
//                }
//                set {
//                    this[this.tablehighscore.tijdColumn] = value;
//                }
//            }
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            public bool IsnaamNull() {
//                return this.IsNull(this.tablehighscore.naamColumn);
//            }
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            public void SetnaamNull() {
//                this[this.tablehighscore.naamColumn] = global::System.Convert.DBNull;
//            }
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            public bool IsscoreNull() {
//                return this.IsNull(this.tablehighscore.scoreColumn);
//            }
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            public void SetscoreNull() {
//                this[this.tablehighscore.scoreColumn] = global::System.Convert.DBNull;
//            }
//        }
        
//        /// <summary>
//        ///Row event argument class
//        ///</summary>
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        public class highscoreRowChangeEvent : global::System.EventArgs {
            
//            private highscoreRow eventRow;
            
//            private global::System.Data.DataRowAction eventAction;
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            public highscoreRowChangeEvent(highscoreRow row, global::System.Data.DataRowAction action) {
//                this.eventRow = row;
//                this.eventAction = action;
//            }
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            public highscoreRow Row {
//                get {
//                    return this.eventRow;
//                }
//            }
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            public global::System.Data.DataRowAction Action {
//                get {
//                    return this.eventAction;
//                }
//            }
//        }
//    }
//}
//namespace Mastermind.mastermindHighscoreDataSetTableAdapters {
    
    
//    /// <summary>
//    ///Represents the connection and commands used to retrieve and save data.
//    ///</summary>
//    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
//    [global::System.ComponentModel.ToolboxItem(true)]
//    [global::System.ComponentModel.DataObjectAttribute(true)]
//    [global::System.ComponentModel.DesignerAttribute("Microsoft.VSDesigner.DataSource.Design.TableAdapterDesigner, Microsoft.VSDesigner" +
//        ", Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")]
//    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
//    public partial class highscoreTableAdapter : global::System.ComponentModel.Component {
        
//        private global::MySql.Data.MySqlClient.MySqlDataAdapter _adapter;
        
//        private global::MySql.Data.MySqlClient.MySqlConnection _connection;
        
//        private global::MySql.Data.MySqlClient.MySqlTransaction _transaction;
        
//        private global::MySql.Data.MySqlClient.MySqlCommand[] _commandCollection;
        
//        private bool _clearBeforeFill;
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        public highscoreTableAdapter() {
//            this.ClearBeforeFill = true;
//        }
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        protected internal global::MySql.Data.MySqlClient.MySqlDataAdapter Adapter {
//            get {
//                if ((this._adapter == null)) {
//                    this.InitAdapter();
//                }
//                return this._adapter;
//            }
//        }
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        internal global::MySql.Data.MySqlClient.MySqlConnection Connection {
//            get {
//                if ((this._connection == null)) {
//                    this.InitConnection();
//                }
//                return this._connection;
//            }
//            set {
//                this._connection = value;
//                if ((this.Adapter.InsertCommand != null)) {
//                    this.Adapter.InsertCommand.Connection = value;
//                }
//                if ((this.Adapter.DeleteCommand != null)) {
//                    this.Adapter.DeleteCommand.Connection = value;
//                }
//                if ((this.Adapter.UpdateCommand != null)) {
//                    this.Adapter.UpdateCommand.Connection = value;
//                }
//                for (int i = 0; (i < this.CommandCollection.Length); i = (i + 1)) {
//                    if ((this.CommandCollection[i] != null)) {
//                        ((global::MySql.Data.MySqlClient.MySqlCommand)(this.CommandCollection[i])).Connection = value;
//                    }
//                }
//            }
//        }
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        internal global::MySql.Data.MySqlClient.MySqlTransaction Transaction {
//            get {
//                return this._transaction;
//            }
//            set {
//                this._transaction = value;
//                for (int i = 0; (i < this.CommandCollection.Length); i = (i + 1)) {
//                    this.CommandCollection[i].Transaction = this._transaction;
//                }
//                if (((this.Adapter != null) 
//                            && (this.Adapter.DeleteCommand != null))) {
//                    this.Adapter.DeleteCommand.Transaction = this._transaction;
//                }
//                if (((this.Adapter != null) 
//                            && (this.Adapter.InsertCommand != null))) {
//                    this.Adapter.InsertCommand.Transaction = this._transaction;
//                }
//                if (((this.Adapter != null) 
//                            && (this.Adapter.UpdateCommand != null))) {
//                    this.Adapter.UpdateCommand.Transaction = this._transaction;
//                }
//            }
//        }
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        protected global::MySql.Data.MySqlClient.MySqlCommand[] CommandCollection {
//            get {
//                if ((this._commandCollection == null)) {
//                    this.InitCommandCollection();
//                }
//                return this._commandCollection;
//            }
//        }
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        public bool ClearBeforeFill {
//            get {
//                return this._clearBeforeFill;
//            }
//            set {
//                this._clearBeforeFill = value;
//            }
//        }
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        private void InitAdapter() {
//            this._adapter = new global::MySql.Data.MySqlClient.MySqlDataAdapter();
//            global::System.Data.Common.DataTableMapping tableMapping = new global::System.Data.Common.DataTableMapping();
//            tableMapping.SourceTable = "Table";
//            tableMapping.DataSetTable = "highscore";
//            tableMapping.ColumnMappings.Add("naam", "naam");
//            tableMapping.ColumnMappings.Add("score", "score");
//            tableMapping.ColumnMappings.Add("tijd", "tijd");
//            this._adapter.TableMappings.Add(tableMapping);
//        }
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        private void InitConnection() {
//            this._connection = new global::MySql.Data.MySqlClient.MySqlConnection();
//            this._connection.ConnectionString = global::Mastermind.Properties.Settings.Default.mastermindConnectionString;
//        }
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        private void InitCommandCollection() {
//            this._commandCollection = new global::MySql.Data.MySqlClient.MySqlCommand[1];
//            this._commandCollection[0] = new global::MySql.Data.MySqlClient.MySqlCommand();
//            this._commandCollection[0].Connection = this.Connection;
//            this._commandCollection[0].CommandText = "SELECT `naam`, `score`, `tijd` FROM `highscore`";
//            this._commandCollection[0].CommandType = global::System.Data.CommandType.Text;
//        }
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
//        [global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Fill, true)]
//        public virtual int Fill(mastermindHighscoreDataSet.highscoreDataTable dataTable) {
//            this.Adapter.SelectCommand = this.CommandCollection[0];
//            if ((this.ClearBeforeFill == true)) {
//                dataTable.Clear();
//            }
//            int returnValue = this.Adapter.Fill(dataTable);
//            return returnValue;
//        }
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
//        [global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Select, true)]
//        public virtual mastermindHighscoreDataSet.highscoreDataTable GetData() {
//            this.Adapter.SelectCommand = this.CommandCollection[0];
//            mastermindHighscoreDataSet.highscoreDataTable dataTable = new mastermindHighscoreDataSet.highscoreDataTable();
//            this.Adapter.Fill(dataTable);
//            return dataTable;
//        }
//    }
    
//    /// <summary>
//    ///TableAdapterManager is used to coordinate TableAdapters in the dataset to enable Hierarchical Update scenarios
//    ///</summary>
//    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
//    [global::System.ComponentModel.ToolboxItem(true)]
//    [global::System.ComponentModel.DesignerAttribute("Microsoft.VSDesigner.DataSource.Design.TableAdapterManagerDesigner, Microsoft.VSD" +
//        "esigner, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")]
//    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapterManager")]
//    public partial class TableAdapterManager : global::System.ComponentModel.Component {
        
//        private UpdateOrderOption _updateOrder;
        
//        private bool _backupDataSetBeforeUpdate;
        
//        private global::System.Data.IDbConnection _connection;
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        public UpdateOrderOption UpdateOrder {
//            get {
//                return this._updateOrder;
//            }
//            set {
//                this._updateOrder = value;
//            }
//        }
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        public bool BackupDataSetBeforeUpdate {
//            get {
//                return this._backupDataSetBeforeUpdate;
//            }
//            set {
//                this._backupDataSetBeforeUpdate = value;
//            }
//        }
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        [global::System.ComponentModel.Browsable(false)]
//        public global::System.Data.IDbConnection Connection {
//            get {
//                if ((this._connection != null)) {
//                    return this._connection;
//                }
//                return null;
//            }
//            set {
//                this._connection = value;
//            }
//        }
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        [global::System.ComponentModel.Browsable(false)]
//        public int TableAdapterInstanceCount {
//            get {
//                int count = 0;
//                return count;
//            }
//        }
        
//        /// <summary>
//        ///Update rows in top-down order.
//        ///</summary>
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        private int UpdateUpdatedRows(mastermindHighscoreDataSet dataSet, global::System.Collections.Generic.List<global::System.Data.DataRow> allChangedRows, global::System.Collections.Generic.List<global::System.Data.DataRow> allAddedRows) {
//            int result = 0;
//            return result;
//        }
        
//        /// <summary>
//        ///Insert rows in top-down order.
//        ///</summary>
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        private int UpdateInsertedRows(mastermindHighscoreDataSet dataSet, global::System.Collections.Generic.List<global::System.Data.DataRow> allAddedRows) {
//            int result = 0;
//            return result;
//        }
        
//        /// <summary>
//        ///Delete rows in bottom-up order.
//        ///</summary>
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        private int UpdateDeletedRows(mastermindHighscoreDataSet dataSet, global::System.Collections.Generic.List<global::System.Data.DataRow> allChangedRows) {
//            int result = 0;
//            return result;
//        }
        
//        /// <summary>
//        ///Remove inserted rows that become updated rows after calling TableAdapter.Update(inserted rows) first
//        ///</summary>
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        private global::System.Data.DataRow[] GetRealUpdatedRows(global::System.Data.DataRow[] updatedRows, global::System.Collections.Generic.List<global::System.Data.DataRow> allAddedRows) {
//            if (((updatedRows == null) 
//                        || (updatedRows.Length < 1))) {
//                return updatedRows;
//            }
//            if (((allAddedRows == null) 
//                        || (allAddedRows.Count < 1))) {
//                return updatedRows;
//            }
//            global::System.Collections.Generic.List<global::System.Data.DataRow> realUpdatedRows = new global::System.Collections.Generic.List<global::System.Data.DataRow>();
//            for (int i = 0; (i < updatedRows.Length); i = (i + 1)) {
//                global::System.Data.DataRow row = updatedRows[i];
//                if ((allAddedRows.Contains(row) == false)) {
//                    realUpdatedRows.Add(row);
//                }
//            }
//            return realUpdatedRows.ToArray();
//        }
        
//        /// <summary>
//        ///Update all changes to the dataset.
//        ///</summary>
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        public virtual int UpdateAll(mastermindHighscoreDataSet dataSet) {
//            if ((dataSet == null)) {
//                throw new global::System.ArgumentNullException("dataSet");
//            }
//            if ((dataSet.HasChanges() == false)) {
//                return 0;
//            }
//            global::System.Data.IDbConnection workConnection = this.Connection;
//            if ((workConnection == null)) {
//                throw new global::System.ApplicationException("TableAdapterManager contains no connection information. Set each TableAdapterMana" +
//                        "ger TableAdapter property to a valid TableAdapter instance.");
//            }
//            bool workConnOpened = false;
//            if (((workConnection.State & global::System.Data.ConnectionState.Broken) 
//                        == global::System.Data.ConnectionState.Broken)) {
//                workConnection.Close();
//            }
//            if ((workConnection.State == global::System.Data.ConnectionState.Closed)) {
//                workConnection.Open();
//                workConnOpened = true;
//            }
//            global::System.Data.IDbTransaction workTransaction = workConnection.BeginTransaction();
//            if ((workTransaction == null)) {
//                throw new global::System.ApplicationException("The transaction cannot begin. The current data connection does not support transa" +
//                        "ctions or the current state is not allowing the transaction to begin.");
//            }
//            global::System.Collections.Generic.List<global::System.Data.DataRow> allChangedRows = new global::System.Collections.Generic.List<global::System.Data.DataRow>();
//            global::System.Collections.Generic.List<global::System.Data.DataRow> allAddedRows = new global::System.Collections.Generic.List<global::System.Data.DataRow>();
//            global::System.Collections.Generic.List<global::System.Data.Common.DataAdapter> adaptersWithAcceptChangesDuringUpdate = new global::System.Collections.Generic.List<global::System.Data.Common.DataAdapter>();
//            global::System.Collections.Generic.Dictionary<object, global::System.Data.IDbConnection> revertConnections = new global::System.Collections.Generic.Dictionary<object, global::System.Data.IDbConnection>();
//            int result = 0;
//            global::System.Data.DataSet backupDataSet = null;
//            if (this.BackupDataSetBeforeUpdate) {
//                backupDataSet = new global::System.Data.DataSet();
//                backupDataSet.Merge(dataSet);
//            }
//            try {
//                // ---- Prepare for update -----------
//                //
//                // 
//                //---- Perform updates -----------
//                //
//                if ((this.UpdateOrder == UpdateOrderOption.UpdateInsertDelete)) {
//                    result = (result + this.UpdateUpdatedRows(dataSet, allChangedRows, allAddedRows));
//                    result = (result + this.UpdateInsertedRows(dataSet, allAddedRows));
//                }
//                else {
//                    result = (result + this.UpdateInsertedRows(dataSet, allAddedRows));
//                    result = (result + this.UpdateUpdatedRows(dataSet, allChangedRows, allAddedRows));
//                }
//                result = (result + this.UpdateDeletedRows(dataSet, allChangedRows));
//                // 
//                //---- Commit updates -----------
//                //
//                workTransaction.Commit();
//                if ((0 < allAddedRows.Count)) {
//                    global::System.Data.DataRow[] rows = new System.Data.DataRow[allAddedRows.Count];
//                    allAddedRows.CopyTo(rows);
//                    for (int i = 0; (i < rows.Length); i = (i + 1)) {
//                        global::System.Data.DataRow row = rows[i];
//                        row.AcceptChanges();
//                    }
//                }
//                if ((0 < allChangedRows.Count)) {
//                    global::System.Data.DataRow[] rows = new System.Data.DataRow[allChangedRows.Count];
//                    allChangedRows.CopyTo(rows);
//                    for (int i = 0; (i < rows.Length); i = (i + 1)) {
//                        global::System.Data.DataRow row = rows[i];
//                        row.AcceptChanges();
//                    }
//                }
//            }
//            catch (global::System.Exception ex) {
//                workTransaction.Rollback();
//                // ---- Restore the dataset -----------
//                if (this.BackupDataSetBeforeUpdate) {
//                    global::System.Diagnostics.Debug.Assert((backupDataSet != null));
//                    dataSet.Clear();
//                    dataSet.Merge(backupDataSet);
//                }
//                else {
//                    if ((0 < allAddedRows.Count)) {
//                        global::System.Data.DataRow[] rows = new System.Data.DataRow[allAddedRows.Count];
//                        allAddedRows.CopyTo(rows);
//                        for (int i = 0; (i < rows.Length); i = (i + 1)) {
//                            global::System.Data.DataRow row = rows[i];
//                            row.AcceptChanges();
//                            row.SetAdded();
//                        }
//                    }
//                }
//                throw ex;
//            }
//            finally {
//                if (workConnOpened) {
//                    workConnection.Close();
//                }
//                if ((0 < adaptersWithAcceptChangesDuringUpdate.Count)) {
//                    global::System.Data.Common.DataAdapter[] adapters = new System.Data.Common.DataAdapter[adaptersWithAcceptChangesDuringUpdate.Count];
//                    adaptersWithAcceptChangesDuringUpdate.CopyTo(adapters);
//                    for (int i = 0; (i < adapters.Length); i = (i + 1)) {
//                        global::System.Data.Common.DataAdapter adapter = adapters[i];
//                        adapter.AcceptChangesDuringUpdate = true;
//                    }
//                }
//            }
//            return result;
//        }
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        protected virtual void SortSelfReferenceRows(global::System.Data.DataRow[] rows, global::System.Data.DataRelation relation, bool childFirst) {
//            global::System.Array.Sort<global::System.Data.DataRow>(rows, new SelfReferenceComparer(relation, childFirst));
//        }
        
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        protected virtual bool MatchTableAdapterConnection(global::System.Data.IDbConnection inputConnection) {
//            if ((this._connection != null)) {
//                return true;
//            }
//            if (((this.Connection == null) 
//                        || (inputConnection == null))) {
//                return true;
//            }
//            if (string.Equals(this.Connection.ConnectionString, inputConnection.ConnectionString, global::System.StringComparison.Ordinal)) {
//                return true;
//            }
//            return false;
//        }
        
//        /// <summary>
//        ///Update Order Option
//        ///</summary>
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        public enum UpdateOrderOption {
            
//            InsertUpdateDelete = 0,
            
//            UpdateInsertDelete = 1,
//        }
        
//        /// <summary>
//        ///Used to sort self-referenced table's rows
//        ///</summary>
//        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//        private class SelfReferenceComparer : object, global::System.Collections.Generic.IComparer<global::System.Data.DataRow> {
            
//            private global::System.Data.DataRelation _relation;
            
//            private int _childFirst;
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            internal SelfReferenceComparer(global::System.Data.DataRelation relation, bool childFirst) {
//                this._relation = relation;
//                if (childFirst) {
//                    this._childFirst = -1;
//                }
//                else {
//                    this._childFirst = 1;
//                }
//            }
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            private global::System.Data.DataRow GetRoot(global::System.Data.DataRow row, out int distance) {
//                global::System.Diagnostics.Debug.Assert((row != null));
//                global::System.Data.DataRow root = row;
//                distance = 0;

//                global::System.Collections.Generic.IDictionary<global::System.Data.DataRow, global::System.Data.DataRow> traversedRows = new global::System.Collections.Generic.Dictionary<global::System.Data.DataRow, global::System.Data.DataRow>();
//                traversedRows[row] = row;

//                global::System.Data.DataRow parent = row.GetParentRow(this._relation, global::System.Data.DataRowVersion.Default);
//                for (
//                ; ((parent != null) 
//                            && (traversedRows.ContainsKey(parent) == false)); 
//                ) {
//                    distance = (distance + 1);
//                    root = parent;
//                    traversedRows[parent] = parent;
//                    parent = parent.GetParentRow(this._relation, global::System.Data.DataRowVersion.Default);
//                }

//                if ((distance == 0)) {
//                    traversedRows.Clear();
//                    traversedRows[row] = row;
//                    parent = row.GetParentRow(this._relation, global::System.Data.DataRowVersion.Original);
//                    for (
//                    ; ((parent != null) 
//                                && (traversedRows.ContainsKey(parent) == false)); 
//                    ) {
//                        distance = (distance + 1);
//                        root = parent;
//                        traversedRows[parent] = parent;
//                        parent = parent.GetParentRow(this._relation, global::System.Data.DataRowVersion.Original);
//                    }
//                }

//                return root;
//            }
            
//            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
//            public int Compare(global::System.Data.DataRow row1, global::System.Data.DataRow row2) {
//                if (object.ReferenceEquals(row1, row2)) {
//                    return 0;
//                }
//                if ((row1 == null)) {
//                    return -1;
//                }
//                if ((row2 == null)) {
//                    return 1;
//                }

//                int distance1 = 0;
//                global::System.Data.DataRow root1 = this.GetRoot(row1, out distance1);

//                int distance2 = 0;
//                global::System.Data.DataRow root2 = this.GetRoot(row2, out distance2);

//                if (object.ReferenceEquals(root1, root2)) {
//                    return (this._childFirst * distance1.CompareTo(distance2));
//                }
//                else {
//                    global::System.Diagnostics.Debug.Assert(((root1.Table != null) 
//                                    && (root2.Table != null)));
//                    if ((root1.Table.Rows.IndexOf(root1) < root2.Table.Rows.IndexOf(root2))) {
//                        return -1;
//                    }
//                    else {
//                        return 1;
//                    }
//                }
//            }
//        }
//    }
}

#pragma warning restore 1591